#!/bin/sh -e

# update/upgrade
# hostname (= 'rp')
# users:
# - delete obsolete users like ubuntu, pi, etc.
# - create user 'user'(+ password)
# - change root-password
# packages
# - docker (by standard repo)
# - transcoder
# - dr14
# - extra tools like htop, net-tools, nano
# create folders (and rights)
# - /media/usbdata
# crontab
# - upgrade
# - transcoder
# - dr14tool
# fstab
#  LABEL=usbdata /media/usbdata ext4 auto,nofail 0 0
# squeezelite
# - config
# copy files
# - rc.local => /etc
#   - enable rc.local system
#   - make rc.local executable
# - lms-config => /etc/docker/lms
